### PR TITLE
Added dir-name-position to the configuration

### PR DESCRIPTION
**Pull request by SmallLars**
Using this option allows to move the directory
name to the root (0.0) or to the leafs (1.0).

### CODE REVIEW

**Comment by SmallLars** [comment]
Relates to #33 and #151

**Comment by acaudwell** [comment]
I kind of like the idea though it doesn't seem to allow putting the label at the centre of the directory (1.0 looks like about 75% along the edge, 0.0 is about 25%).

Its more likely people will want to control it being between the middle of the edge and at the centre of the directory. For instance 0% would be at the centre of the previous directory which wouldn't make sense.

It might just be simpler to make it add an option for putting at the midpoint.

**Comment by SmallLars** [comment]
> I kind of like the idea though it doesn't seem to allow putting the label at the centre of the directory (1.0 looks like about 75% along the edge, 0.0 is about 25%).

Yes, I ignored the spline point. On a straight line its in the middle, With 0.0/1.0 the text ist between the middle and the endpoint 25%/75%. For me that was enough.

> Its more likely people will want to control it being between the middle of the edge and at the centre of the directory. For instance 0% would be at the centre of the previous directory which wouldn't make sense.
> 
> It might just be simpler to just add an option for putting at the midpoint.

I will adjust the formular, to reach 0%/100%. It is not a big deal.

**Comment by SmallLars** [comment]
[p1_quota](http://m.wolframalpha.com/input/?i=%281+-+%280.5+-+abs%28p+-+0.5%29%29%29+*+%281+-+p%29), [p2_quota](http://m.wolframalpha.com/input/?i=%281+-+%280.5+-+abs%28p+-+0.5%29%29%29+*+p), [s_quota](http://m.wolframalpha.com/input/?i=0.5+-+abs%28p+-+0.5%29)

[Sum](http://m.wolframalpha.com/input/?i=%280.5+-+abs%28p+-+0.5%29%29%2B%28%281+-+%280.5+-+abs%28p+-+0.5%29%29%29+*+%281+-+p%29%29%2B%28%281+-+%280.5+-+abs%28p+-+0.5%29%29%29+*+p%29) is 1 at every time.

**Comment by acaudwell** [comment]
Nice.

**Pull request merged**
