### PR TITLE
Add loop-delay-seconds option

### PR DESCRIPTION
**Pull request by joeyparrish**
Before looping, optionally delay some number of seconds.

### CODE REVIEW

**Comment by acaudwell** [comment]
Could you use auto-skip-seconds there or do you think its likely you'd want a different value? Perhaps it should use auto-skip-seconds if loop-delay-seconds is 0.

**Comment by joeyparrish** [comment]
Sorry, I don't understand what you mean.  Should auto-skip-seconds have this as a side-effect?  What is its main effect?  I'm looking at --help, and I don't understand what it is meant to do.

`-a, --auto-skip-seconds SECONDS  Auto skip to next entry if nothing happens for a number of seconds (default: 3)`

**Comment by acaudwell** [comment]
If there's no activity for N seconds, it skips ahead in time to the next commit in history instead of incrementing time bit by bit as it normally would (e.g. imagine a sparse project where there is no activity for weeks or months).

If its looping, the next entry to skip to is the first entry was my thinking, it just doesn't currently do that it appears.

**Comment by joeyparrish** [comment]
Ah, okay.  I understand now.  So would this PR be okay in its current form?  I'd be happy to make changes if you think it's necessary.

And thanks for reviewing it!

**Comment by acaudwell** [comment]
I was trying to avoid adding another variable if we can use the existing one. i.e. you could change your change to use the auto_skip_seconds variable, unless you think we really need them to be different values.

**Comment by joeyparrish** [comment]
I tend to think different variables is clearer and easier to understand.  Why would auto_skip_seconds have two different effects at two different times?  Wouldn't this overloading be confusing and cause unintended side-effects for some people at some time?  Wouldn't this make maintenance a little more difficult/subtle?  What would be the benefit of combining them?

**Comment by acaudwell** [comment]
I'll keep it as a different command line option but default it to auto_skip_seconds (skipping to the next entry in the log after a period of inactivity. i.e. the start of the log when looping).

**Comment by joeyparrish** [comment]
Thank you so much for your consideration!

**Pull request merged**
