### PR TITLE
Commits per author

### PR DESCRIPTION
**Pull request by rlucca**
Hi there,

It's a initial version of a totalize of commits per author to your review. This uses the FileKey class and overload the inc() and dec() method to do the thing. :)

Thank you

### CODE REVIEW

**Comment by acaudwell** [comment]
Thanks for this. Will have a look at it soon.

**Comment by Kickball** [comment]
@acaudwell are you still going to review this?

**Comment by rlucca** [comment]
@acaudwell if you need I change something just tell me. :)

**Comment by acaudwell** [comment]
I notice when the author is removed from the list you see a negative commit count as it fades out. Maybe there should be some way to control the width of the author name as it will usually be truncated if it is someones full name. Could maybe allow adjusting this with the mouse (non trivial change I know).

Maybe there should be a variation showing the file change count per author instead of commits (might be more intuitive as the default).

First impressions, I think this is a useful feature.

Sorry about not getting around to looking at this until now!

**Comment by rlucca** [comment]
File change count could be better conceptually because I think it is wrong expire commits. But commit count is a usefull thing too. I'll see about keep both in my code and not expire the commits. How should be called the later one? --ranking-commit-author?

**Comment by rlucca** [comment]
@acaudwell,

I changed the settings to accept 5 news options: --author, --author-mode (file|commit), --text-rectangle-width <NUMBER>, --key-at-right and --author-at-right. The last two options are to put the stats at right of screen. The text-rectangle-width is to control the length of authors and extensions. The labels are always align at left. Author mode specify if it is file change counting or commit counting. File change counting is expired by "file-idle-time" option.

**Comment by acaudwell** [comment]
Sorry I'm apprehensive about merging this because it can be seen as or used as a tool to rank developers even if that's not the intention.

**Comment by rlucca** [comment]
yeah, it is not the original intention... Thanks for give a final decision. :)

**Pull request closed without merging**
