### PR TITLE
adapt README to GitHub markdown

### PR DESCRIPTION
**Pull request by schmidtdominik**
take a look at my fork to see the fully rendered readme:

image

### CODE REVIEW

**Comment by brodock** [comment]
:+1: for formatted README in markdown :)

**Comment by mschilli87** [comment]
Any reason this was never merged? https://github.com/acaudwell/Gource/issues/123 was closed now but is not 'resolved'.

**Comment by acaudwell** [comment]
I was thinking I wanted a solution where I only maintain one set of documentation rather than two (man page and README). I had a bit of a look into it but didn't progress from there...

**Comment by brodock** [comment]
maybe using something like the kramdown converter to man pages: https://kramdown.gettalong.org/converter/man.html

**Comment by jehy** [comment]
I raelly liked this repo so I wanted to add travis integration for building gource. But without md readfile there is no place to put a cute badge...

**Comment by PF94** [comment]
kinda confused why @acaudwell doesn't appect it,

**Comment by ljacqu** [comment]
https://github.com/acaudwell/Gource/pull/29#issuecomment-384183328 is pretty clear as to the reason

**Comment by ZurMaD** [comment]
Hmm end of 2020 and the documentation on Github is really old, maybe you can add just here two files. Like INSTALL and INSTALL.md

**Comment by Potherca** [comment]
I think pandoc would be a good match... Simply running `pandoc -f man -t markdown gource.1 > README.md` already gives something workable: https://github.com/potherca-contrib/Gource/tree/feature/README-from-MAN

I'm fairly confident things could be improved and/or added to your build pipeline quite easily.

@acaudwell Is this something that would be a better match for your needs? If so. I wouldn't mind setting it up for you.

**Comment by acaudwell** [comment]
I've converted the current README to Markdown similar to @schmidtdominik original pull request.

**Pull request closed without merging**
